[juliaextra]
git-tree-sha1 = "66e744fbf39bab71c2f63b6877a506fee8fbc9a5"
lazy = true

    [[juliaextra.download]]
    sha256 = "61133afa7e06fda133f07164c57190a5b922f8f2a1aa17c3f8a628b5cf752512"
    url = "https://github.com/svilupp/AIHelpMeArtifacts/raw/main/artifacts/juliaextra__v1.10.0__ada1.0.tar.gz"
